{"LogId":null,"Status":"Razor engine module adding error.","DateTime":"2/27/2023 12:35:25 PM","LogType":4,"Error":"{\"s\":\"Core .Net SqlClient Data Provider\",\"st\":\"   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken)\\r\\n   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)\\r\\n   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)\\r\\n   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\\r\\n   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\\r\\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\\r\\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\\r\\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\\r\\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\\r\\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\\r\\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\\r\\n   at System.Data.SqlClient.SqlConnection.Open()\\r\\n   at Kachuwa.Data.CrudService`1.GetList(String conditions, Object parameters) in C:\\\\Users\\\\rahul\\\\Downloads\\\\LiveTrainingSourceCodeWithDBBackup\\\\LiveTraining\\\\LiveTraining\\\\Kachuwa\\\\Kachuwa.Core\\\\Data\\\\Crud\\\\CrudService.cs:line 138\\r\\n   at Kachuwa.Web.Module.ModuleRegistrar.Register() in C:\\\\Users\\\\rahul\\\\Downloads\\\\LiveTrainingSourceCodeWithDBBackup\\\\LiveTraining\\\\LiveTraining\\\\Kachuwa\\\\Kachuwa.Web\\\\Module\\\\ModuleRegistrar.cs:line 64\",\"ie\":{\"ClassName\":\"System.ComponentModel.Win32Exception\",\"Message\":\"A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond\",\"Data\":null,\"InnerException\":null,\"HelpURL\":null,\"StackTraceString\":null,\"RemoteStackTraceString\":null,\"RemoteStackIndex\":0,\"ExceptionMethod\":null,\"HResult\":-2147467259,\"Source\":null,\"WatsonBuckets\":null,\"NativeErrorCode\":10060},\"data\":{\"HelpLink.ProdName\":\"Microsoft SQL Server\",\"HelpLink.EvtSrc\":\"MSSQLServer\",\"HelpLink.EvtID\":\"10060\",\"HelpLink.BaseHelpUrl\":\"http://go.microsoft.com/fwlink\",\"HelpLink.LinkId\":\"20476\"},\"HelpLink\":null}"}

{"LogId":null,"Status":"A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 0 - A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.)","DateTime":"2/27/2023 12:36:55 PM","LogType":4,"Error":"{\"s\":\"Core .Net SqlClient Data Provider\",\"st\":\"   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken)\\r\\n   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)\\r\\n   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)\\r\\n   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\\r\\n   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\\r\\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\\r\\n   at System.Data.ProviderBase.DbConnectionPool.WaitForPendingOpen()\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at Kachuwa.Data.CrudService`1.InsertAsync(Object entityToInsert) in C:\\\\Users\\\\rahul\\\\Downloads\\\\LiveTrainingSourceCodeWithDBBackup\\\\LiveTraining\\\\LiveTraining\\\\Kachuwa\\\\Kachuwa.Core\\\\Data\\\\Crud\\\\CrudService.cs:line 233\\r\\n   at Kachuwa.Web.AuditAttribute.OnActionExecutionAsync(ActionExecutingContext context, ActionExecutionDelegate next) in C:\\\\Users\\\\rahul\\\\Downloads\\\\LiveTrainingSourceCodeWithDBBackup\\\\LiveTraining\\\\LiveTraining\\\\Kachuwa\\\\Kachuwa.Web\\\\Service\\\\Audit\\\\AuditAttribute.cs:line 62\",\"ie\":{\"ClassName\":\"System.ComponentModel.Win32Exception\",\"Message\":\"A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond\",\"Data\":null,\"InnerException\":null,\"HelpURL\":null,\"StackTraceString\":null,\"RemoteStackTraceString\":null,\"RemoteStackIndex\":0,\"ExceptionMethod\":null,\"HResult\":-2147467259,\"Source\":null,\"WatsonBuckets\":null,\"NativeErrorCode\":10060},\"data\":{\"HelpLink.ProdName\":\"Microsoft SQL Server\",\"HelpLink.EvtSrc\":\"MSSQLServer\",\"HelpLink.EvtID\":\"10060\",\"HelpLink.BaseHelpUrl\":\"http://go.microsoft.com/fwlink\",\"HelpLink.LinkId\":\"20476\"},\"HelpLink\":null}"}

